add check for services and add flags for debug in run (test pending)

diff --git a/scripts/config b/scripts/config
--- a/scripts/config
+++ b/scripts/config
@@ -11,10 +11,19 @@ UI_PORT_EXT="$(grep listen $PROJECT_ROOT/nginx/services/ui.conf | cut -d':' -f2 
 API_PORT_EXT="$(grep listen $PROJECT_ROOT/nginx/services/api.conf | cut -d':' -f2 | tr -d ';')"
 EXTERNAL_PORTS="$UI_PORT_EXT $API_PORT_EXT 5601"
 LOGDIR=$PROJECT_ROOT/logs
+SERVICES=("api" "ui" "nginx" "es" "vis")
 
 function is_running {
   # Usage: is_running CONTAINER
   echo $(podman ps | grep $1 | wc -l)
+}
+
+function check_service {
+  # Usage: check_service SERVICE_NAME
+  if ! [[ " ${SERVICES[*]} " == *" $1 "* ]]; then 
+    echo "Invalid service name: $1"
+    exit 1 
+  fi
 }
 
 function user_input {
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -6,16 +6,32 @@ source config
 
 ! [ $1 ] && echo "Missing argument" && exit 1
 
-CONTAINER=$1
+CONTAINER=$1; shift 1
 TAG=$REPO/$APP:$CONTAINER
 CONTEXT="$(get_context $CONTAINER)"
-OPTIONS="-d --rm --name $APP-$CONTAINER --pod $APP"
+OPTIONS="-d --name $APP-$CONTAINER --pod $APP"
+
+check_service $CONTAINER
+
+# Parse command line arguments
+while (( "$#" )); do
+  case "$1" in
+    --dev) DEV=true && shift 1;;
+    --debug) DEBUG=true && shift 1;;
+    --) shift && break;; # End of arguments
+    *) echo "Error: Unsupported flag $1" >&2 && exit 1;;
+  esac
+done
+
+if ! [ "$DEBUG" ]; then
+  OPTIONS="$OPTIONS --rm"
+fi
 
 if [ -f "$CONTEXT/.env" ]; then
   OPTIONS="$OPTIONS --env-file $CONTEXT/.env"
 fi
 
-if [ "$2" = "--dev" ] && { [ $CONTAINER = "api" ] || [ $CONTAINER = "ui" ] ;}; then
+if [ "$DEV" ] && { [ $CONTAINER = "api" ] || [ $CONTAINER = "ui" ] ;}; then
   OPTIONS="$OPTIONS -v $CONTEXT/$CONTAINER:/$CONTAINER/$CONTAINER"
   if [ $CONTAINER = "api" ]; then
       OPTIONS="$OPTIONS -v $CONTEXT/tests:/$CONTAINER/tests"
